### ISSUE TITLE
lazy update error

### ISSUE THREAD

**Issue by gyl30** [willothy/nvim-cokeline#166] opened 2023-09-17 09:55 UTC
When I run lazy update or lazy install, I get an error. Can you help me see what's going on?

<img width="1440" alt="图片" src="https://github.com/willothy/nvim-cokeline/assets/48873542/cf0c154e-4041-4b6d-86e2-32fb64acbf2f">

**Comment by gyl30** [comment] 2023-09-17 09:56
Here's my configuration.

```
return {
  "willothy/nvim-cokeline",
  dependencies = {
    "nvim-lua/plenary.nvim",
    "kyazdani42/nvim-web-devicons",
  },
  config = true
}

```

**Comment by willothy** [comment] 2023-09-17 16:20
Thanks for reporting! I'll look into this today.

**Comment by willothy** [comment] 2023-09-17 20:17
What version of Neovim are you using?

**Comment by gyl30** [comment] 2023-09-18 01:04
```
NVIM v0.9.2
Build type: Release
LuaJIT 2.1.0-beta3

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
/home/linuxbrew/.linuxbrew/Cellar/neovim/0.9.2/share/nvim"

Run :checkhealth for more info


```

**Comment by willothy** [comment] 2023-09-18 03:12
Thanks!

**Comment by willothy** [comment] 2023-09-18 03:54
Just pushed 13dd53b which updated the default config to use the updated highlight group functions - I haven't been able to reproduce, but can you let me know if that fixes it once you update?

**Comment by gyl30** [comment] 2023-09-18 06:18
Updated to 9d2ec14 Same error, I think I need to provide more info but I don't know which ones I need

**Comment by willothy** [comment] 2023-09-18 07:19
What colorscheme are you using / do you have `termguicolors` enabled? Could help narrow things down, it's possible that there are some edge cases with older color schemes.

**Comment by gyl30** [comment] 2023-09-18 13:25
I am using the theme [vscdoe](https://github.com/Mofiqul/vscode.nvim), echo &termguicolors output is 1

**Comment by willothy** [comment] 2023-09-21 01:07
I have not been able to reproduce this. Could you try to create a minimal init config that can reproduce the issue? Thanks

**Comment by gyl30** [comment] 2023-09-22 05:36
I've created a Minimized Configuration [Repository](https://github.com/gyl30/cokeline.git), can you take a look at it for me?

**Comment by willothy** [comment] 2023-09-22 05:49
Sure, I'll try that out. Has that repo been confirmed to reproduce the issue with the default cokeline config? It looks like you're using the `get_hex` function in there, which is deprecated, so not sure if that could be related.

Also, as a sidenote, generally you should provide a single file that can be copy-pasted as a minimal init. The idea is that it can be tested with `nvim --clean -u minimal.lua` to make reproducing quicker, without having to download an entire nvim config. For this one it's alright tho, I'll look at the repo if that can reproduce the issue.

**Comment by willothy** [comment] 2023-09-22 06:06
Enabling cache in lazy.nvim fixed the issue for me. Not sure why this would be the case, I'll keep looking into it, but let me know if that fixes it for you.

**Comment by willothy** [comment] 2023-09-22 06:13
Actually, using `require("cokeline.hlgroups").get_hl_attr` instead of `get_hex` fixes it for me as well. You should use that function instead of `get_hex` as is suggested in the readme, because it uses the Lua/C API instead of vimscript and caches results to avoid repeated lookups. I'm closing this as I've concluded this to be the issue, but if that fix doesn't help then feel free to reopen.

**Closed by willothy** 2023-09-22 06:13 UTC

**Comment by gyl30** [comment] 2023-09-22 06:17
I reproduced the problem using the following configuration, and it looks like it is indeed caused by get_hex

```
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
    vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", "--branch=stable",
        lazypath })
end

vim.opt.rtp:prepend(lazypath)

local cokeline_config = function()
    local get_hex = require('cokeline.utils').get_hex
    -- require('cokeline').setup()                  -- 1
    require('cokeline').setup({                     -- 2
        default_hl = {
            fg = function(buffer)
                return
                    buffer.is_focused
                    and get_hex('Normal', 'fg')
                    or get_hex('Comment', 'fg')
            end,
            bg = 'NONE',
        },
    })
end

require("lazy").setup({
    {
        "willothy/nvim-cokeline",
        dependencies = {
            "nvim-lua/plenary.nvim",
        },
        config = cokeline_config,
    },
    'Mofiqul/dracula.nvim',
    'Mofiqul/vscode.nvim'        
})

```

**Comment by gyl30** [comment] 2023-09-22 06:19
Notice the two comments in the code, when I use the code in the first place there is no error. When I use the code in the second place, there is an error

**Comment by willothy** [comment] 2023-09-22 06:22
Yeah, `get_hex` should not be used. It was deprecated because it has many issues due to relying on VimScript calls. I'll likely remove it entirely soon. The new highlight APIs are in `cokeline.hlgroups`, and should not cause any issues.

**Comment by gyl30** [comment] 2023-09-22 06:23
Yes, problem solved, thank you very much. Nice plugin

**Comment by willothy** [comment] 2023-09-22 06:23
Thanks! Glad I could help, sorry it took so long.
