### ISSUE TITLE
Add tab indicator?

### ISSUE THREAD

**Issue by tmpm697** [willothy/nvim-cokeline#92] opened 2023-01-15 08:58 UTC
I know this is a buffer bar but i currently use this and also try to distinguish what's tab i'm currently on and don't want to use another bar for it.

like this: https://github.com/kdheepak/tabline.nvim --> i want tab indicator at top right

Is is possible to add that info to cokeline?

**Comment by willothy** [comment] 2023-03-25 11:31
Definitely would like to add an option to group by tabs, as well as to collapse tab groups, will link PR when I start working on it.

**Comment by willothy** [comment] 2023-03-27 23:57
Closing as duplicate of #35, updates will be posted there.

**Closed by willothy** 2023-03-27 23:57 UTC
Labels: duplicate
