### ISSUE TITLE
'style'-attribute of component has no effect

### ISSUE THREAD

**Issue by fabiobaser** [willothy/nvim-cokeline#156] opened 2023-08-23 14:09 UTC
not one single component respects the style option. Using existing hl_group works.

`{
	text = function(buffer)
		return buffer.filename
	end,
	style = "italic",
},`

**Comment by willothy** [comment] 2023-08-23 16:41
Duplicate of #154, the style property was removed in 0.4 in favor of individual properties.

**Closed by willothy** 2023-08-23 16:41 UTC
