### ISSUE TITLE
[question] all tabs are closed ?

### ISSUE THREAD

**Issue by livrth** [willothy/nvim-cokeline#95] opened 2023-01-20 14:44 UTC
I find a interesting logic that when I use the:
```lua
map('n', '<leader>w', '<Plug>(cokeline-pick-close)', { silent = true })
```

to close tabs. If I close the tab I'm focusing now, then all tabs are closed. That's really wired. 

<img width="1385" alt="image" src="https://user-images.githubusercontent.com/45538642/213724817-80ec5621-ed40-43b6-87d8-7d35c5f4a7b5.png">

For example, now I'm focusing on the tab 3 with a picker `f`. If I close the `f`, then all tabs are closed....

What I want to do is only "close any tab I want" instead of closing all tabs.

My config file is here:

<details> <summary>config.lua</summary>

```lua
local get_hex = require('cokeline/utils').get_hex
local mappings = require('cokeline/mappings')
local is_picking_focus = require('cokeline/mappings').is_picking_focus
local is_picking_close = require('cokeline/mappings').is_picking_close

local comments_fg = get_hex('Comment', 'fg')
local errors_fg = get_hex('DiagnosticError', 'fg')
local warnings_fg = get_hex('DiagnosticWarn', 'fg')

local red = vim.g.terminal_color_1
local yellow = vim.g.terminal_color_3

local components = {
  space = {
    text = ' ',
    truncation = { priority = 1 }
  },

  two_spaces = {
    text = '  ',
    truncation = { priority = 1 },
  },

  {
    text = function(buffer)
      return
        (is_picking_focus() or is_picking_close())
        and buffer.pick_letter .. ' '
        or buffer.devicon.icon
    end,
    fg = function(buffer)
      return
        (is_picking_focus() and yellow)
        or (is_picking_close() and red)
        or buffer.devicon.color
    end,
    style = function(_)
      return
        (is_picking_focus() or is_picking_close())
        and 'italic,bold'
        or nil
    end,
  },

  separator = {
    text = function(buffer)
      return buffer.index ~= 1 and '▏' or ''
    end,
    truncation = { priority = 1 }
  },

  devicon = {
    text = function(buffer)
      return
        (mappings.is_picking_focus() or mappings.is_picking_close())
        and buffer.pick_letter .. ' '
        or buffer.devicon.icon
    end,
    fg = function(buffer)
      return
        (mappings.is_picking_focus() and yellow)
        or (mappings.is_picking_close() and red)
        or buffer.devicon.color
    end,
    style = function(_)
      return
        (mappings.is_picking_focus() or mappings.is_picking_close())
        and 'italic,bold'
        or nil
    end,
    truncation = { priority = 1 }
  },

  index = {
    text = function(buffer)
      return buffer.index .. ': '
    end,
    truncation = { priority = 1 }
  },

  unique_prefix = {
    text = function(buffer)
      return buffer.unique_prefix
    end,
    fg = comments_fg,
    style = 'italic',
    truncation = {
      priority = 3,
      direction = 'left',
    },
  },

  filename = {
    text = function(buffer)
      return buffer.filename
    end,
    style = function(buffer)
      return
        ((buffer.is_focused and buffer.diagnostics.errors ~= 0)
        and 'bold,underline')
        or (buffer.is_focused and 'bold')
        or (buffer.diagnostics.errors ~= 0 and 'underline')
        or nil
    end,
    truncation = {
      priority = 2,
      direction = 'left',
    },
  },

  diagnostics = {
    text = function(buffer)
      return
        (buffer.diagnostics.errors ~= 0 and '  ' .. buffer.diagnostics.errors)
        or (buffer.diagnostics.warnings ~= 0 and '  ' .. buffer.diagnostics.warnings)
        or ''
    end,
    fg = function(buffer)
      return
        (buffer.diagnostics.errors ~= 0 and errors_fg)
        or (buffer.diagnostics.warnings ~= 0 and warnings_fg)
        or nil
    end,
    truncation = { priority = 1 },
  },

  close_or_unsaved = {
    text = function(buffer)
      return buffer.is_modified and '●' or ''
    end,
    fg = function(buffer)
      return buffer.is_modified and yellow or nil
    end,
    delete_buffer_on_left_click = true,
    truncation = { priority = 1 },
  },
}

require('cokeline').setup({
  show_if_buffers_are_at_least = 2,

  sidebar = {
    filetype = 'NvimTree',
    components = {
      {
        text = '    SOURCE FILE TREE',
        fg = yellow,
        bg = get_hex('NvimTreeNormal', 'bg'),
        style = 'bold',
      },
    }
  },

  buffers = {
    -- filter_valid = function(buffer) return buffer.type ~= 'terminal' end,
    -- filter_visible = function(buffer) return buffer.type ~= 'terminal' end,
    new_buffers_position = 'next',
  },

  rendering = {
    max_buffer_width = 30,
  },

  default_hl = {
    fg = function(buffer)
      return
        buffer.is_focused
        and get_hex('Normal', 'fg')
        or get_hex('Comment', 'fg')
    end,
    bg = get_hex('ColorColumn', 'bg'),
    -- bg = get_hex('NvimTreeNormal', 'bg'),
  },

  components = {
    components.space,
    components.separator,
    components.space,
    components.devicon,
    components.space,
    components.index,
    components.unique_prefix,
    components.filename,
    components.diagnostics,
    components.two_spaces,
    components.close_or_unsaved,
    components.space,
  },
})

local map = vim.api.nvim_set_keymap

map('n', '<Leader>e', '<Plug>(cokeline-focus-prev)', { silent = true })
map('n', '<Leader>i', '<Plug>(cokeline-focus-next)', { silent = true })
map('n', '<leader>w', '<Plug>(cokeline-pick-close)', { silent = true })
```
</details>

Any solutions? Thanks!

**Comment by willothy** [comment] 2023-03-26 03:28
I believe this could be caused by bdelete not preserving window layout, as in #44. Working on resolving this ASAP.

**Closed** 2023-03-27 01:36 UTC
